/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ehxeeiwrvapnbpghipac"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVoeGVlaXdydmFwbmJwZ2hpcGFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAwNDM1NTcsImV4cCI6MjA4NTYxOTU1N30.aEVd_O1LR-9Nc3NYFinZPVs4gaF5t3GoXhP4qFYX0Vc"
